### ISSUE TITLE
Missing ConditionClinicalStatus enumeration

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#106]
There is no `ConditionalClinicalStatus` enumeration in https://github.com/ewoutkramer/fhir-net-api/blob/master/src/Hl7.Fhir.Core/Model/Generated/Condition.cs corresponding to the possible values of http://hl7.org/fhir/condition-definitions.html#Condition.clinicalStatus

**Comment by ewoutkramer** [comment]
We only generate valuesets for codes that are 'required', this one is 'preferred'.  The problem is that if we generate a member for ClinicalStatus of an enumerated type, you could never assign any other codes to it, and since the binding is 'preferred', we need to be able to do this. 

One way is to generate a list of Code-instances (so, not a native enum), which could then be used. This would be a major breaking change however...

**Comment by michelemottini** [comment]
I see, thanks.

You could leave the `Condition.ClinicalStatus` as a string and still create the `ConditionClinicalStatus` enumeration (that is what we did in our code) - this would not break anything I think

(Obviously not important / major in any way)

**Comment by brianpos** [comment]
As a preferred valueset can't restrict to the enum approach as this would prevent other systems being used.
