### ISSUE TITLE
Unable to get practitioner details via search

### ISSUE THREAD

**Issue by taramoskam** [ewoutkramer/fhir-net-api#130]
I'm trying to access a practitioner's details via UHN's DSTU2 server.
I have downloaded the NuGet package for DSTU2.

The code is as follows in an ASP.NET MVC application.

var client = new FhirClient("http://fhirtest.uhn.ca/baseDstu2");
Bundle results;

results = client.Search<Practitioner>(new string[] { "_id=22529"});
//this does return a bundle with the practitioner I am searching for

foreach (var entry in results.Entry)
{
          //here I am unable to access the practitioners address/birthdate, etc.
          var address = entry.Resource..... (there is no option to choose address/gender/birthdate)
}

When I open the returned object, I can see the address/birthdate but I can not access it, as once resource is opened, the next drop down is [Hl7.Fhir.Model.Practitioner] which I can not get into with any of the available commands.

Please assist :)

**Comment by ewoutkramer** [comment]
Ø  var address = entry.Resource..... (there is no option to choose address/gender/birthdate)

The problem is that entry.Resource is of type Resource, so, you won’t have access to all the specific properties, unless you cast entry.Resource to the actual type, so

Var address = ((Patient)(entry.Resource)).Address;

That should work….

   Ewout

**Comment by taramoskam** [comment]
Thank you so much ! You are absolutely correct!
