### ISSUE TITLE
SearchParams.FromUriParamList throws on empty parameters

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#148]
Something like `.../Patient?family=` is possible, even if not legal, and I don't think it should cause `FromUriParamList()` to throw

**Comment by brianpos** [comment]
This routine I believe returns string parameters, even if the parameter should be a date.

**Comment by ewoutkramer** [comment]
This is just URI level parsing, so `UriParamList.FromQueryString("family=");` returns a list of key/value Tuples, which indeed are both strings.   However, SearchParams.FromUriParamList() takes such a list and separates them into "regular" parameters and well known special FHIR params (like _include and _element), and types those from the last category so you have an easier interface.  I think we should enforce that the values are not empty, since this is illegal in FHIR. In fact, I currently explicitly throw an exception when the value is empty...

Why should I not do that?

**Comment by michelemottini** [comment]
Empty parameters are not allowed, so (I think) they should cause an error 400 with an OperationOutcome explaining the nature of the error (e.g. ''Parameter xxx cannot be empty'). Currently `FromUriParameterList()` throws an `ArgumentException()` that causes the server to fail with an error 500 and some generic / non-informative message. Catching ALL `ArgumentException` and converting them to error 400 is not a great solution, and trying to figure out which specific `ArgumentException` you are dealing with is not easy.

I'd say it would be probably better of `FromUriParameterList()` let the empty parameters be, leaving the error handling to the actual parameter parsing - that must already have logic to generate appropriate error messages.

**Comment by ewoutkramer** [comment]
Maybe the ArgumentNill  is indeed not the best (since the argument isn't null, there's a wrong parameter with no contents), and I will throw FormatException instead.

**Comment by ewoutkramer** [comment]
Closing this issue, since it has been merged.
