### ISSUE TITLE
How to Parse a Bundle

### ISSUE THREAD

**Issue by rajarameshvarma** [ewoutkramer/fhir-net-api#192]
In the initial version of the API I remember seeing SerializeBundleToJson. But I no longer see that.
I am using nuget package HL7.FHIR.DSTU21.

I am trying to return a patient list from my Web API.

```
public IHttpActionResult Get()
        {
            Bundle bundle = new Bundle();
            foreach(Patient patient in Patients.Get())
            {
                bundle.AddResourceEntry(patient, Url.Route("DefaultApi", new { Controller = "Patient", id = patient.Id }));
            }
         
            //parse bundle                             
        }
```

How can I parse the bundle here.

Thanks

**Comment by mbaltus** [comment]
Parsing a Bundle would mean taking json/xml content and parse that into an in memory Bundle object, but what you describe is the other way around: making json from an in memory object (= serialization).
To do that you can still use the FhirSerializer in Hl7.Fhir.Serialization. Since DSTU2 a Bundle is a real FHIR Resource, so there was no need for a separate method to serialize bundles anymore. You can now just use the regular Resource serialization:

` 
               var jsonText = FhirSerializer.SerializeResourceToJson(bundle);
`

**Comment by rajarameshvarma** [comment]
Thank you @mbaltus
