### ISSUE TITLE
Can AllowedTypes on Extension.Value[x] be fully specified?

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#215]
On the property Value of Extension, there are these attributes:

``` csharp
[FhirElement("value", InSummary=true, Order=40, Choice=ChoiceType.DatatypeChoice)]
[AllowedTypes(typeof(Hl7.Fhir.Model.Element))]
```

This is the only type that has this. In other cases, the list of AllowedTypes is fully specified. For example in Timing.RepeatComponent:

``` csharp
[FhirElement("bounds", InSummary=true, Order=40, Choice=ChoiceType.DatatypeChoice)]
[AllowedTypes(typeof(Hl7.Fhir.Model.Duration),typeof(Hl7.Fhir.Model.Range),typeof(Hl7.Fhir.Model.Period))]
```

This prevents me from expanding the canonical name of the property ("value") to the type-specified names ("valueInteger", "valueReference", etc.) in a generic way.

Is het possible to simply provide the full list of allowed types on Extension.Value as well?

**Comment by ewoutkramer** [comment]
Yes, since this is the only place in the spec (well, I think Parameter.value[x] will have it too) that allows *any* type, so that's any subclass from Element.  

I understand your position though: it seems it would make sense for the POCO generator to expand this list, so all users of these attributes don't have to do this.

**Comment by ewoutkramer** [comment]
The new T4 generator actually does this, but since Extension is maintained by hand, this change did not make it into Extension. Fixed.
