### ISSUE TITLE
create FHIR version independent package

### ISSUE THREAD

**Issue by eugene-sergueev** [ewoutkramer/fhir-net-api#253]
Do you have any thoughts to split package on Core (Base resource, serialization/deserialization) which has no dependencies on FHIR version (DSTU, STU) and Model - FHIR version specific?

**Comment by ewoutkramer** [comment]
I sure have.  The current assemblies can be split along functionality that is version-independent, connected to the use of POCOs or not, lower/higher level FhirClient functionality, REST, parsing etc. 

I would like to do that once I move to .NET Core, since in the .NET Core world the tendency is to split up codebases into many more assemblies than we used to. 

For .NET Core, I am waiting for the next tooling drop to start working, although newer packages (e.g. the Fhir FluentPath implementation) are already on Core.

**Comment by ewoutkramer** [comment]
Let me just add: we're now converting to netstandard and will start splitting up the assembly shortly.  Though there will often be dependencies on the version: the FhirClient, the parsers, the validator etc. they will keep a dependency on the POCO models, and thus are DSTU2/STU3 specific. We are working on a new set of classes to read instance data on a "DOM" basis, see here for my presentation about it: http://www.slideshare.net/ewoutkramer/advanced-net-api-ewout (first few slidees)
