### ISSUE TITLE
AutoFixture not supported with fhir-net-api models

### ISSUE THREAD

**Issue by Scott-Lyons** [ewoutkramer/fhir-net-api#261]
In our unit tests we heavily rely on AutoFixture to create anonymous models. When trying to create an anonymous fhir model the following error occurs: 

`OneTimeSetUp: System.ArgumentException : Type BundleProxy is not a mappable Fhir datatype or resource
Parameter name: type
  Exception doesn't have a stacktrace` 

Is there any plans to support AutoFixture or any known work around to this issues? It seems to be an compatibility issue between the models used in fhir and the way AutoFixture creates anonymous models.

**Comment by ewoutkramer** [comment]
Hi Scott,

Could you explain what an "anonymous" model is?  The "Type XXXX is not a mappable Fhir datatype" comes from the reflection code that lists the contents of all FHIR model (generated) classes, which in turn configure the parsers/serializers. 

All classes that are being fed to the serializer/parser need to be labelled with the [FhirType] attribute, including the classes that these types refer to.  So, if the framework proxies these classes, you somehow have to make sure the [FhirType] attribute is retained too, since it contains valuable information for the serializer and parser.

**Comment by Karrakunga** [comment]
Hi Ewout,

Another definition for anonymous models is auto-generated variables. So AutoFixture will take a complex or primitive type and auto populate it to aide with setup during unit testing.

I don't know the underlying code of AutoFixture but it does sound like your description is the issue. We have worked around this by not relying on AutoFixture specifically for HL7 Fhir models.

**Comment by brianpos** [comment]
Looks like the AutoFixture creates a proxy class derived from the FHIR Model class and tries to use that.
I guess it then tries to pretend other information is then coming out when asked.
This may not be a good idea for FHIR objects, but not sure.
The fhir models have lots of cases where a 2 properties are using the same backing data (private internals) which convert the FHIR datatype into a native .NET type, as they don't quite always match.
Will have to investigate further (we don't use AutoFixture, so can't be sure)

**Comment by brianpos** [comment]
in our code we are hand writing example objects with specific data that we want to test.
We used to do this via XML example files that we load in, but then changed to coded tests so that when updating versions of FHIR was easier to catch differences. (and when we rename stuff in the model we try and include obsolete attributes on the old properties with a compile error to help guide upgrades)

**Comment by brianpos** [comment]
Given the way this feature works, and the way the current serialization works (via reflection) anonymous proxy objects likely won't work.

**Comment by brianpos** [comment]
Given it's been a while and no comments on this with current implementation, closing it.
