### ISSUE TITLE
Hl7.Fhir.Search namespace

### ISSUE THREAD

**Issue by prsmith1** [ewoutkramer/fhir-net-api#273]
Hi,

I've downloaded the DSTU2 Nuget package, and I'm looking for the Hl7.Fhir.Search namespace, but it isn't available.

In http://ewoutkramer.github.io/fhir-net-api/assemblies-overview.html it says you can use the objects contained within to help build queries.

Is this available as part of the nuget package (I have version 0.90.5?)

Thanks,
Piers

**Comment by ewoutkramer** [comment]
Ouch, that's an old namespace that disappeared after DSTU1.  Must admit that page is way too old....

**Comment by mbaltus** [comment]
Although that page is old, there is of course functionality in the API to be able to search. You could take a look at the FhirClient and SearchParams in the Hl7.Fhir.Rest part of the package. See the [fhirstarters github](https://github.com/furore-fhir/fhirstarters) for a very basic search example.

**Comment by prsmith1** [comment]
Thanks for your response - yep that's fine. It turns out that the libraries are a bit too comprehensive for my use anyway. Do you know if there is a library out there that has just the FHIR model objects as POCO entities, with no dependencies on anything else, or is there an easy way of generating this?

**Comment by ewoutkramer** [comment]
I am planning to split up the library into smaller bits, "just the model" being one of them. However, I'd like to do this when we move to .NET Core, since in the "core" world smaller assemblies are the new norm.  But otherwise, you could just download the source code, and remove everything but the Model namespace (well, you probably need some of the supporting namespaces, but not the parsers and fhir client) and then build.  

The C# classes are generated using T4 templates, so you could even change them a bit to remove the attributes you don't need.....

**Comment by prsmith1** [comment]
I was thinking about doing that but then noticed the dependencies to the other namespaces, but if it is just the attributes though that doesn't sound too bad. I might give this a go if I get time. Thanks very much for your help anyway.
