### ISSUE TITLE
Cannot get DocumentReference

### ISSUE THREAD

**Issue by gthompson83** [ewoutkramer/fhir-net-api#345]
When attempting to read a DocumentReference i get the following error: 

Additional information: Must be a FHIR REST url containing the resource type in its path

`var location = new Uri("https://pro171.open.allscripts.com/FHIR/Patient/4/DocumentReference");
 var doc = client.Read<DocumentReference>(location);`

Using that same location through another API testing tool works just fine.

**Comment by brianpos** [comment]
Looks like as issue using the compartment format.

**Comment by brianpos** [comment]
Actually, looking closet, that's a search as it will be returning a bundle of document references for that patient. So think you need to use search.

**Comment by gthompson83** [comment]
How would I structure the command for a search? I can't find a reference of this anywhere online.

**Comment by ewoutkramer** [comment]
The client complains since the given URL is not a FHIR REST url identifying a resource - which is what Read() expects.  I cannot see whether this is a search or not, what you could do is try a client.Get(), which allows you to give ANY endpoint url and will return any kind of resource, either a Patient or a Bundle (if this is a search)
