### ISSUE TITLE
Hl7.Fhir.Support net40 support

### ISSUE THREAD

**Issue by u8621011** [ewoutkramer/fhir-net-api#363]
Is Hl7.Fhir.Support possible to support net40 platform?

We saw that Hl7.Fhir.DSTU2 an Hl7.FhirPath have net40 platform but Hl7.Fhir.Support not, is that jsut a missing piece?

**Comment by ewoutkramer** [comment]
Hi Ted,

We have dropped support for net40.  Hl7.fhir.support is built on dotnet standard - and we have moved our whole codebase to dotnet standard, which does not support net4.0.

That being said, we've supported net 4.0 for a long time, so it should still be possible to compile at least .NET API Core for net4 (not .NET API Specification, since it needs zip support).

**Comment by lstratman** [comment]
I actually forked and added support for the net40 target to Hl7.Fhir.STU3, Hl7.Fhir.Support, and Hl7.FhirPath with a minimum of fuss.  The vast majority of the divergence between the two targets was around reflection and things being moved from Type to TypeInfo, so once I implemented a TypeInfo polyfill for net40 with the required methods and properties, it worked great and the maintenance going forward should be pretty minimal.

I can send a PR if you would like.

**Comment by ewoutkramer** [comment]
Yes, please!

**Comment by u8621011** [comment]
Great Job and thanks for your sharing~  @lstratman

**Comment by ewoutkramer** [comment]
I will pull the PR.

**Comment by brianpos** [comment]
Yes, thanks for the contribution.
