### ISSUE TITLE
Organization vs ManagingOrganization

### ISSUE THREAD

**Issue by lmallette** [ewoutkramer/fhir-net-api#364]
In DTSU-2 under PractitionerRole we should have a Organization instead we have a ManagingOrganization.

**Comment by mbaltus** [comment]
Are you sure you're using the DSTU2 package?
In DSTU2 you have Practitioner.PractitionerRoleComponent.ManagingOrganization, which is correct according to the DSTU2 specification.
In STU3 this field has been removed from the Practitioner resource. Instead we now have a new resource type: PractitionerRole. That resource has Organization as one of its fields. So if you're using the STU3 library, you will find PractitionerRole.Organization, which is correct according to the STU3 specification.

**Comment by lmallette** [comment]
Yes. I was on STU3 before and got the problem with the PractitionerRole so I change for DSTU-2. 

Base on https://hl7.org/fhir/DSTU2/practitioner.html#def, you are right with ManagingOrganization but base on http://hl7.org/fhir/2016sep/practitionerrole.html its Organization not ManagingOrganization and the server answering my request his using DSTU2 with a "Organization" under PractitionerRole note ManagingOrganization. 

So which version of Fhir.Net DSTU2 should I use to have Organziation  instead of ManagingOrganization?

thanks

**Comment by mbaltus** [comment]
The 2016sep you mention is also STU3, so that has the PractitionerRole resource.

Questions: What are you trying to retrieve from the server, and what is the response? What was the problem you had with the PractitionerRole when you used STU3?

If the server answers you with a PractitionerRole resource, then it is an STU3 server and you need to use the Hl7.Fhir.STU3 package. You could also check the FHIR version of the server by retrieving the server's metadata.

**Comment by lmallette** [comment]
here a sample of the XML sent by the server:

<...>
   <Practitioner xmlns="http://hl7.org/fhir">
                <...>
                <practitionerRole>
                <...>
                        <Organization>
                                    <...>


At first I try with Fhir.Net with STU3 thinking that it was backward
compatible with Fhir DTSU-2 (the server I call suppose to be DTSU-2).

But I got this error when doing client.Read<Practitioner>("Practitioner/" +
idPractitioner) : Encountered unknown member 'practitionerRole' while
de-serializing.

So I did my research and found out the different between STU3 and DTSU-2
for this part. So I remove Fhir.Net STU3 and use Fhir.Net DTSU-2 instead.

Now with the same call I have this error : Encountered unknown member
'organization' while de-serializing.

I done other research and found that the server his suppose to be DTSU-2
1.0.2 ... but like you said .. this version use ManagingOrganization and
not Organization.

The meta return from the server does not seem to have the official version
of it. But the server documentation gives me this URL:
http://hl7.org/fhir/dstu2/. Base on that its 1.0.2 and you are right.

The server I call does not respect the standard and I think that the server
does not use Fhir.Net ...

Sorry for the false issue ;o).

Thanks for the help.

**Comment by mbaltus** [comment]
Yes, I agree that the server seems to send data that is not completely FHIR compliant. They put the Organization resource within the managingOrganization tag, instead of just using a reference.
If you need to test your software, you can also use one of the publicly available test servers listed here: http://wiki.hl7.org/index.php?title=Publicly_Available_FHIR_Servers_for_testing.
Can you please close this issue after reading this?

**Comment by lmallette** [comment]
thanks for your help
