### ISSUE TITLE
Parsing Condition resource with multiple Stages

### ISSUE THREAD

**Issue by Sushant-Sardeshpande** [ewoutkramer/fhir-net-api#373]
Client: STU3 - ver. 0.93.4

I do know that FHIR specifies that a condition can have Stage with a cardinality in between 0 and 1, however the server we are communicating is sending us an array of Stages to support our current use case.
I was told that strictness or conformance to a resource could be configurable to support overriden attributes. Is there a way to do that in this client, if not could it be added.

Thanks in advance.

**Comment by ewoutkramer** [comment]
Hi Li-Shezaar,

Strictness is indeed configurable, but a compliant server may only be more strict, and may never widen cardinalities. So, if the FHIR specification has 0..* for an element, servers may choose to support only 0..1.  If, however the FHIR specification says an element is 0..1, servers can never widen this to 0..*, since that would break compatibility with clients.  

In this case, since the specification has 0..1 for stage, a server returning multiple stages is *incompliant* with the spec, and the API will not be able to read its data. 

As a matter of fact, the cardinality of stage will indeed be made into 0..* for release 4 of FHIR (due in about 16 months), so you might be talking to a server implementing the latest nightly build (check http://build.fhir.org/condition.html for the newest).  As far as I know, the common clients (like those for .NET and Java) haven't yet an R4 update available.

Please verify with the server developer whether they are using STU3 or indeed the nightly build. In the latter case, it will take some time before HL7 will publish a "snapshot" of the nightly build that's stable enough for client developers like me to update to.

**Comment by Li-Shezaar** [comment]
Hello,
They are using STU3 specification for this and it seems the attribute has been overriden to add more parameters. Could it be handled equivalent to a custom resource or is it a fix that should be done by the FHIR server implementation?
Thanks in advance

**Comment by ewoutkramer** [comment]
This is a fix that should be done by the server. In STU3, there is simply no more than 1 stage for a Condition, unless the server has added some (custom) <extension> elements to Condition to make this work, but if I read your question correctly, they are simply repeating the <stage> field  - which is not STU3 compliant in any way.
