### ISSUE TITLE
Transitive output of specification.zip

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#416]
Currently I copy the specification.zip from the NuGet package directory manually to my own project, and include it in the output there. It should be possible to do this automatically, to transitively take the output from the Hl7.Fhir.Specification package to the output of my own project.

If I understand https://github.com/NuGet/Home/issues/4837 correctly, I think this can be enabled when specification.zip is being output to 'contentFiles' rather than to 'content'.

I think this should be changed in Hl7.Fhir.Specification.csproj, at the Content Include=specification.zip, just change the PackagePath to contentFiles.

**Comment by wmrutten** [comment]
Excellent suggestion!


I frequently have to update Forge to a new FHIR API package. After the update, NuGet always resets the Build Action of specification.zip to "None". Without further action, the ZIP file would no longer be included in the binary output folder nor in the ClickOnce installer package. So each time, I have to take care to manually reset the Build Action back to "Content". This is annoying and error prone...

**Comment by ewoutkramer** [comment]
So, I have fixed this by using the new NuGet facilities for <PackageReference> and transitive behaviour. In short:

* Since NuGet 3.3 there's are new .nuspec tags (contentFiles) to better support transitive includes
* Using <contentFiles> I can now set the Build Action without needing to resort to powershell files in the Nuget zip - this ps file wasn't executed anymore anyway in the latest nuget versions - as it turned out.
* I have managed to alter the .csproj file for Specification so it will generate a .nuspec with the correct new tags
* This means I no longer need the hacky powershell file and I am using built-in facilities in NuGet to control transitive behaviour
* As a side effect, Specification now needs NuGet 3.3 or higher - then again the current NuGet file didn't function anymore anyway. And 3.3 isn't THAT new anymore.
