### ISSUE TITLE
Native .NET datatype returned for fields of datetime in many resouces is string instead of DateTime

### ISSUE THREAD

**Issue by vsmahesh** [ewoutkramer/fhir-net-api#430]
The associated properties that returns .NET native datatype equivalent for `Hl7.Fhir.Model.Medication.BatchComponent.ExpirationDateElement` (ExpirationDate) and `Hl7.Fhir.Model.Immunization.DateElement` (Date) are giving back string instead of DateTime. In fact, it looks like this is the case for most of the non-string data-types with the exception of the one in `Hl7.Fhir.ModelBinary.Content`.

**Comment by ewoutkramer** [comment]
Yes, they are, and this is by design.  The FHIR `dateTime` type (which is the type of these elements) can be _partial_ - ie. just contain a year, or year+date.  The native .NET DateTime cannot handle those situations, so there's no way I can use `DateTime` here, and instead chose to return `string`.
