### ISSUE TITLE
The Json parser should throw an exception when encountering duplicate properties.

### ISSUE THREAD

**Issue by emanuelmd** [ewoutkramer/fhir-net-api#437]
Hello, just as the title states the Json parser doesn't throw an exception when encountering a duplicate property whereas the XML parser does throw one, which is the desired behavior. I'll attach two resources, xml and json which help reproduce the scenario. The resources are two Patients and have a duplicate "active" property.

[sample.zip](https://github.com/ewoutkramer/fhir-net-api/files/1375519/sample.zip)

**Comment by grahamegrieve** [comment]
What I desired should be a setting.

Grahame

**Comment by emanuelmd** [comment]
That would be an option as well, but if you want to keep consistency, the XML parser should support the same setting.

**Comment by ewoutkramer** [comment]
Hi @emanuelmd, for XML, it's natural for elements to repeat, there is no other way since XML does not have a feature comparable to json's array construct.  So, you'll see lots of repeating elements in XML.  

For Json, the situation is different: According to the [RFC for Json](https://www.ietf.org/rfc/rfc4627.txt), the property names SHOULD be unique, that's indeed not a MUST.  According to [this](https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object/21833017), the json library indeed parses repeating properties, ignoring the earlier ones. It does not allow me to construct such an output however, so that's one way.

I will see if I can make this is a setting in json - but I need the Newtonsoft library to support that - otherwise there's no way to know there are duplicate names.

**Comment by ewoutkramer** [comment]
Well, at least that is clear: https://github.com/JamesNK/Newtonsoft.Json/issues/931

James Newton writes:
"Oh I misunderstood. There is no way in Json.NET to restrict them. It will use the last value."

So, it will silently ignore the previous occurrences - nothing we can do about that.
