### ISSUE TITLE
FhirJsonParser any configuration which can improve performance?

### ISSUE THREAD

**Issue by ankgupta067** [ewoutkramer/fhir-net-api#471]
Currently i see a difference of almost 2 times during deserialization  when using fhirjsonparser as compared to fhirxmlparser.  Is there a way to optimize it using some settings or configuration?

**Comment by ewoutkramer** [comment]
In the latest version we're working on now (0.94.x) we've rewritten the parsers to get them as fast as we currently can.  There will always be a difference between the FHIR json format and xml, since the json format *may* split up properties in two (one prefixed with an underscore).  This means that some lookup scanning is involved.

We plan to release an alpha of this version this week, maybe you can try it out (again this is *alpha*), and see if it makes a difference!

**Comment by ewoutkramer** [comment]
It's now available on beta-2 on NuGet - let me know if you still have issues.

**Comment by ankgupta067** [comment]
from where i can get this package?
Right now i am using this one-
Install-Package Hl7.Fhir.DSTU2 -Version 0.92.5

**Comment by brianpos** [comment]
https://www.nuget.org/packages/Hl7.Fhir.STU3/0.94.0-beta2

**Comment by ankgupta067** [comment]
yes i ticked include pre release and it was there thanks
