### ISSUE TITLE
memory-eating beast

### ISSUE THREAD

**Issue by jkiddo** [ewoutkramer/fhir-net-api#488]
Having used forge where I had 10 profiles and 5 extensions opened at the same time, forge ended up eating 1.2 GB mem. Its hard for me to tell where the bug is (could be here in the api or it could be forge), but something seems to eat a lot of my mem.

**Comment by ewoutkramer** [comment]
Hi Jens, is there anything that leads you to believe it's the api, or is this an invitation for us to research that ourselves? ;-)

**Comment by ewoutkramer** [comment]
The interesting thing here is that both Michel and I believe we are very aware of memory consumption and try to minimize it in the API - but Forge does cache a lot, since it runs on a desktop, not a mobile phone....

**Comment by brianpos** [comment]
Its not chewing things up in my server which uses the client for validation and serialization...

**Comment by wmrutten** [comment]
I'd have to investigate further. Considering the feedback above, the issue seems to be specific to Forge.

Note that Forge leverages the API to perform snapshot generation _on steroids_ (to be able to calculate yellow pen). Possibly the additional custom work generates additional memory pressure. This could explain why servers don't seem to be affected.

Another likely candidate for possible memory leaks is the WPF UI layer. The application uses e.g. weak references and weak events to prevent keeping strong references to UI components, but it's quite easy to overlook (implicit) strong references, so there's probably still room for improvement here.

**Comment by ewoutkramer** [comment]
I am taking the liberty of this being either a forge issue or a forge feature (use the memory you have to cache & be as responsive as possible).

If we have further concrete clues the API is the source of the issue, pls reopen with additional information.
