### ISSUE TITLE
Internal Sprache parser causes conflicts

### ISSUE THREAD

**Issue by mattiasflodin** [ewoutkramer/fhir-net-api#553]
If an application depends on both fhir-net-api and the [Sprache](https://www.nuget.org/packages/Sprache/) NuGet packages, then you will get a compilation error like so:

`error CS0433: The type 'Parser<T>' exists in both 'Hl7.FhirPath, Version=0.94.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' and 'Sprache, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null'
`

This is caused by the internal copy of the Sprache source code that exists in Hl7.FhirPath. It's possible to get around the compilation error by removing the dependency on Sprache and using the one provided by Hl7.FhirPath, but doing so limits the ability to upgrade to newer versions of Sprache. I would suggest that either the copied Sprache code is put under a HL7 namespace to prevent the conflict, or that the copy is removed in favor of an external dependency on the Sprache NuGet package.

**Comment by ewoutkramer** [comment]
I have been using Sprache internally mainly since Sprache was not packaged as a signed assembly - so I could not turn it into an external dependency (since the FHIR API is signed).  Also, I am cautious to add new external dependencies (in big companies, every third party dependency & their dependencies need to be vetted and agreed on), and lastly, it seemed nicholas blumhardt seemed to have moved on to other things (Superpower).

If Sprache is now distributed as a signed assembly, then we can change it to an external dependency...

**Comment by mattiasflodin** [comment]
There is a signed version. But maybe a less invasive change would be to just put the internal Sprache code into the Hl7 namespace.

**Comment by ewoutkramer** [comment]
Yes, let's do that.

**Comment by ewoutkramer** [comment]
Fixed by #797

**Comment by wmrutten** [comment]
By the way, [Superpower](https://github.com/datalust/superpower) looks pretty nice.
Also see this [Blog article](https://nblumhardt.com/2016/09/superpower/).

Any plans to update from Sprache to this new parser library?
