### ISSUE TITLE
DateExtensions.ToFhirDateTime produces dateTimes without timezones if DateTime.Kind is Unspecified

### ISSUE THREAD

**Issue by eug48** [ewoutkramer/fhir-net-api#627]
Another one of those date-related issues I'm afraid.. Currently we seem to have the following:

1. `DateExtensions.ToFhirDateTime(DateTime)` calls `PrimitiveTypeConverter.ConvertTo<string>`
2. `PrimitiveTypeConverter` eventually calls `XmlConvert.ToString((DateTime)value, FMT_FULL)`
3. `XmlConvert.ToString` just calls `DateTime.ToString(format, DateTimeFormatInfo.InvariantInfo)` ([see source)](https://referencesource.microsoft.com/#System.Xml/System/Xml/XmlConvert.cs,764)
4. Now FMT_FULL is "yyyy-MM-dd'T'HH:mm:ss.FFFK" but that last K [outputs nothing if DateTimeKind is Unspecified](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-k-custom-format-specifier)

Perhaps FMT_FULL should have "zzz" instead of "K", or there should be an exception, or these extension methods should only apply to DateTimeOffset values?

**Comment by ewoutkramer** [comment]
So, we're in a catch-22, since use of the "zzz" modifier is not recommended with DateTime values, and "K" produces nothing when DateTimeKind is unspecified.

The root of the problem -as usual- is that we don't know anything about the timezone.  So, should we assume the server's timezone in `DateTime.ToFhirDateTime`, and thus make sure DateTimeKind is never unspecified anymore?  

Yes, DateTime is the hole, I have used DateTimeOffset internally everywhere.

**Comment by eug48** [comment]
I think assuming the timezone is potentially going to introduce some silent data corruption, especially these days when cloud-based servers are often run in a different timezone to their users.

Perhaps an overload taking `DateTimeOffset` could be added to `DateTime.ToFhirDateTime` and the current `DateTime` overload be placed behind a deprecation warning?

**Comment by ewoutkramer** [comment]
Sounds like a plan, I'll look into it.

**Comment by ewoutkramer** [comment]
oops, didn't mean to close it.
