### ISSUE TITLE
Parsing Reference Range

### ISSUE THREAD

**Issue by JeffHumphry** [ewoutkramer/fhir-net-api#674]
Sent and email to fhirapi@fire.ly as well, but thought I would post here to keep it official.

-------------------

I’m having trouble parsing Reference Range Components.

This code snippet below simulates our system receiving a FHIR observation message and saving the reference range component to a DB table column as JSON. Then simulates the retrieval from the DB to rebuild the reference range.

            // Serialize and Parse Reference Range Component *************************************************************

            // Create Reference Range Component
            var refRange = new ReferenceRangeComponent
            {
                Low = new SimpleQuantity { Value = 74, Unit = "[ft_i]", Code = "http://unitsofmeasure.org" },
                High = new SimpleQuantity { Value = 104, Unit = "[ft_i]", Code = "http://unitsofmeasure.org" }
            };
            // Serialize
            var refRangeJson = fhirJsonSerializer.SerializeToString(refRange);
            // Saved to DB table JSON column

            // --------------------------------

            // Retrieve from DB to rebuild FHIR observatoin object
            // Parse
            // Throws System.InvalidOperationException: 
            // 'Root object has no type indication (resourceType) and therefore cannot be used to construct the navigator. 
            // Alternatively, specify a rootName using the parameter.'
            ReferenceRangeComponent parsedRefRange = fhirJsonParser.Parse<ReferenceRangeComponent>(refRangeJson);

The last line is giving me an error: System.InvalidOperationException: 'Root object has no type indication (resourceType) and therefore cannot be used to construct the navigator. Alternatively, specify a rootName using the parameter.'
I do notice that if I manually insert the property "resourceType":"referenceRangeComponent" into the JSON string before I parse it works fine.

2 questions on this:
1.	Why would it give me an error saying that I need the resourceType element in the JSON when I’m specifying the type in <T> in the Parse()?
2.	If I really do need the resourceType element in the JSON, how can I get that to be emitted by the fhirJsonSerializer when it serializes so it will be there for the parser?

Thanks!

Jeff Humphry
Senior Software Architect | New Ocean Health Solutions
Eight Tower Bridge | 161 Washington Street, Suite 1110 | Conshohocken, PA 19428
610.952.9698 (m)

**Comment by wmrutten** [comment]
Hi @JeffHumphry, basically, the FHIR spec is based on the exchange of information in the form of FHIR *resources*. In this case, you're trying to (de-)serialize a resource *component*. This falls outside of the scope of the FHIR spec and the API never aimed to support this.
Nevertheless, I can see how this might be useful in some specific use cases. If you're feeling up to it, pull requests are welcome!

**Comment by ewoutkramer** [comment]
Yes, that's certainly part of it. In fact, as you have discovered, the API tries to let you parse a datatype - I had imagined users would want to do that, but as @wmrutten says, the spec actually has not described features for serializing parts of a resource, and that part therefore is buggy (esp. the code looking for resourceType).

I have just rewritten this part (it will be released after summer) - but I have hit a wall, it is simply impossible to store partial serialized parts, especially in json:

E.g. imagine a primitive datatype (say Boolean) with an extension and the element is called "active". This works in XML:

```xml
<active value='true'><extension></extension></active>
```

But this has no equivalent in json:

```
"active": "true",
"_active": [ { "extension":.....} ]
```

As you can see, the single element in xml turns into two properties in json.  So, you'd say we serialize it as an object:

```
{
   "active": "true",
   "_active": [ { "extension":.....} ]
}
```

but now we have an object in json that represents a property - it's no longer FHIR, since there "active" and "_active" would always be part of a larger object (say Patient). To put it differently, the serialized subtree in Json is not actually what would appear as a subtree when you would serialize the whole resource (here, active would be part of the larger Patient resource).  So we start to deviate from the FHIR spec here. 

This is where I have stopped, also in the new version of the parser - it will tell you you simply cannot do this in JSON.  That's probably too strict (you could do it when the subtree is representing a complex type - no "value" involved), but that's where we are at this moment.

**Comment by ewoutkramer** [comment]
BTW: If you are sure you are never going to serialize a primitive type in the DB column, you could take a look at fixing the bug (since the check for resourceType is a bug - just as it is a bug that it will serialize a 'resourceType' member, even when serializing a subtree).

**Comment by JeffHumphry** [comment]
Thanks Ewout and Michel.

Thanks for the information. I may take a look at this suggested bug fix, time permitting.

For now, I just cobbled some code in my method to add the “resourceType” to the JSON manually before parsing.

Although it sounds like you are saying that your next release may have a change that will fix the bug that’s allowing that, so I’ll need to keep an eye on that.

Thanks,
Jeff Humphry
Senior Software Architect | New Ocean Health Solutions
Eight Tower Bridge | 161 Washington Street, Suite 1110 | Conshohocken, PA 19428
610.952.9698 (m)
