### ISSUE TITLE
Resource.resourceType FHIRPath expression is not supported

### ISSUE THREAD

**Issue by johnstairs** [ewoutkramer/fhir-net-api#744]
The FHIRPath expression `Resource.resourceType` does not evaluate to anything, whereas `Resource.id` does. Is this by design?

**Comment by ewoutkramer** [comment]
Yes.

The "resourceType" is not a real member of Resource, it just appears in the Json serialization as a property (XML uses the root node to indicate the type for example).

There are some operators to work with types within the FhirPath language itself (http://hl7.org/fhirpath/ section 6.3).

Also, since I wrote the interpreter, we have been working on more metadata functions for FhirPath (see section 9 at the same link) - but I have not implemented that yet.

**Comment by johnstairs** [comment]
Thanks for the explanation.
