### ISSUE TITLE
Validation issue with text.div?

### ISSUE THREAD

**Issue by alexzautke** [ewoutkramer/fhir-net-api#756]
Currently, Vonk is throwing an internal server error when trying to serialise the attached Patient resource. The problem is caused by an invalid content in the text.div element. However, when calling $validate with this resource, HTTP 200 is returned.

Could you please check why the validator is accepting this resource?

[Patient.txt](https://github.com/ewoutkramer/fhir-net-api/files/2537967/Patient.txt)

**Comment by brianpos** [comment]
The text element is not a valid xhtml value, it should be like the below and it should load ok
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">testje</div>"
  },

**Comment by brianpos** [comment]
Vonk may even return an OperationOutcome that has this location as where the issue is, and what the problem was.

**Comment by alexzautke** [comment]
Yes that's completely true. But, shouldn't the validator also flag the content as invalid? We were running into the issue because validation is disabled by default on the production environment of Vonk, so it was written as is into the database. But even with validation enabled, it would have been accepted.

**Comment by brianpos** [comment]
Then this is likely a vonknissue rather than fhir-net-api

**Comment by cknaap** [comment]
We could check this in Vonk, but I would have expected to validator to return an error on a Narrative that is not valid xhtml.
This unittests shows it outside the context of Vonk. It fails currently.

```csharp
using Hl7.Fhir.Model;
using Hl7.Fhir.Serialization;
using Hl7.Fhir.Specification.Source;
using Hl7.Fhir.Validation;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Hl7.Fhir.Specification.Tests.Validation
{
    [TestClass]
    public class NarrativeValidationTests
    {

        [TestMethod]
        public void NarrativeMustBeValidXml()
        {
            var json = "{\"resourceType\": \"Patient\", \"text\": \"text without div\"}";
            var patient = new FhirJsonParser().Parse<Patient>(json);
            var validationSource = new CachedResolver(ZipSource.CreateValidationSource());
            var validator = new Validator(new ValidationSettings() { ResourceResolver = validationSource, EnableXsdValidation = true });
            var validationResult = validator.Validate(patient);
            Assert.IsFalse(validationResult.Success, "Expect failure on narrative without <div>");
        }
    }
}
```

**Comment by ewoutkramer** [comment]
Hi all, the new parsers are way more strict about this, and would catch this - if enabled.  Validating xml within a json payload requires another parse (xml parser) + validate (xsd schema) steps. So, even in the new json parser it may well be I did not enable this by default.  I agree, the Validator should *enable* the validation - validation is expensive anyway.

**Comment by ewoutkramer** [comment]
After examination, it turns out that the parser would currently *not* catch this.  The reason is that this validation is done by the ITypedElement parser - since that has type information it knows that an element contains "xhtml", so only then it will try to validate the XML buried within the json.

The same is true for the use of Json arrays when an element repeats: you need to have type information before you know an element repeats. This is also not validated currently when parsing to a POCO.

Why is this?  Because the POCO parser runs on top of ISourceNode, not on top of ITypedElement. This basically means the POCO parser circumvents the validations done by the ITypedElement parsers. 

The solution is to replace the old ComplexTypeReader - and make it work on ITypedElement instead of ISourceNode.  

So, to fix this "small" issue, we'll have to revise this pretty old part of the API. @gstoian feels brave enough to take a stab at this ;-)

**Comment by ewoutkramer** [comment]
I have removed the [Validator] label, since this "validation" isn't done by the Profile-based validator, this is a structural/lower-level check that should be done by the ITypedElement parser.
