### ISSUE TITLE
How to add long value to Resource.Meta.LastUpdated element instead of dateTime value ?

### ISSUE THREAD

**Issue by bharathy403** [ewoutkramer/fhir-net-api#835]
Q1)I want to add tick value to lastupadtedtime of meta resource. As I see it's accepting only datetime and datetimeoffset object which returns me value like
"lastUpdated": "2019-01-14T18:40:38.4479432+05:30" but I want to get values in long type like "LastUpdated" : 636800751033136900.

Q2)Is there any way to store lastUpdatedtime of meta resource in array.??
"LastUpdated" : [
			636800751033136900,
			0
		],

Any lead would be much appreciated!

**Comment by bharathy403** [comment]
Detail and codes related to my issue :
- I am creating a new practitioner object like below :
           var practitioner = new Practitioner();
-Adding meta info to practitioner object like below :
          var metObj = new Meta(); 
-I want to save long value (i.e ticks) instead of DateTime value for "Meta.LastUpdated" property like given below :
         metObj.LastUpdated = DateTime.Now.Ticks;
        
-Also, i want to save list of long data type value in "Meta.LastUpdate" property like given below :
        List<long> lastUpdatedLst = new List<long>();
        lastUpdatedLst.Add(DateTime.Now.Ticks);
        metaObj.LastUpdatedList = lastUpdatedLst;

 I want to know how to achieve above two things!

**Comment by mbaltus** [comment]
The FHIR specification has defined that meta.lastUpdated is of type instant. That datatype is defined like this:

> An instant in time in the format YYYY-MM-DDThh:mm:ss.sss+zz:zz (e.g. 2015-02-07T13:28:17.239+02:00 or 2017-01-01T00:00:00Z).

See http://www.hl7.org/fhir/resource.html#Meta and http://www.hl7.org/fhir/datatypes.html#instant

This API follows the FHIR specification, so you cannot achieve what you want with it, because what you want is not FHIR compliant.

You can however create your own additions to classes, since they are all implemented as partial classes. So you could add a field for the ticks to the meta to be used in your internal code. But please note that whenever you need to communicate your data externally, those ticks cannot be included other than by using an extension.
