### ISSUE TITLE
After serialization to JSON format, either "URL" or "Reference property" of "Identifier.Assigner" class is getting serialized but not both.

### ISSUE THREAD

**Issue by bharathy403** [ewoutkramer/fhir-net-api#836]
->I am creating new "Practitioner" and "Identifier" resource like shown below : 
     var practitioner = new Practitioner();
      var identifier = new Identifier();

->And, adding "Assigner" details to "Identifier" object like given below :
            identifier.Assigner = new ResourceReference();
            identifier.Assigner.Reference = "http://facebook.com";
            identifier.Assigner.Url = new Uri(@"http://xyz.com");
            practitioner.Identifier.Add(identifier);

->After serializing the above object using "FhirJsonSerializer" i am getting below mentioned json where i can only see "Reference" value but not "Url" value of "Assigner" :
"identifier": [{		
		"assigner": {
			"reference": "http://facebook.com"
		}
	}]

-->Expected JSON outcome :
"identifier": [{		
		"assigner": {
			"reference": "http://facebook.com",
                        "url":"http://xyz.com"

		}
	}]

**Comment by mbaltus** [comment]
It seems your FHIR knowledge is lacking a bit, which is why you do not know what you can expect to be in your outcome. You confuse Resources and datatypes, and also your reference is not a correct FHIR reference. Perhaps you could benefit from a [FHIR training](https://fire.ly/training/)?

Issues here are meant for reporting bugs in the API, or to make a suggestion of improving it. For general questions about working with the FHIR API, you can use this Google group: https://groups.google.com/forum/?#!forum/fhir-dotnet.
